window.LIKEWHAT_PATTERNS.push(
  {
    id:'ive-self-possession-editorial',brand:'IVE',family:'Idol / Identity System',collectionType:'idol-era',era:'I HAVE / IVE',name:'IVE — Self-possession Editorial',oneLiner:'「何を持っているか」を、ためらわず見せる。自己肯定を装飾ではなく構図にする。',
    description:'IVEのグループ名「I HAVE＝IVE」と、公式プロフィールにある「私、そして私たちが持っているものを、IVEらしく堂々とした姿で見せる」という決意を、Self-possession Editorialとして抽象化する。憧れを遠い幻想として作るのではなく、本人が既に価値を持っている前提で、視線・余白・短い断定文を使ってConfidenceを設計する。',
    tags:['Self-possession','Aspirational Confidence','Editorial Poise','I HAVE','Composed Glamour'],uiParts:['Editorial','Identity','Statement','Collection'],visual:['人物や主役を中央に小さく置かず、画面の重心として扱う','長い説明より短い断定文で自己確信を作る','装飾を増やさず余白と視線で高級感を出す','複数メンバーを同一化せず、同じフレーム規則で個性を揃える'],useCases:['ファッションEditorial','プレミアムブランド','プロフィール','自信を伝えるキャンペーン'],avoid:['親密さを最優先する日記型コンテンツ','制度説明'],prompt:'IVEの「I HAVE」のように、価値をこれから獲得するのではなく、すでに持っているものを堂々と見せる構図にしてください。短い断定文、余白、強い視線、整った反復で自己確信を作り、過剰な装飾で高級感を代用しないでください。',sourceLabel:'IVE JAPAN OFFICIAL — PROFILE',sourceUrl:'https://ive-official.jp/mob/pageShw.php?cd=profile&site=DIVE',mock:'idol-ive-have',domain:'Culture / Idol',medium:'Fashion Editorial + Music',archetype:'Self-possession Editorial',interactionModel:'Meet confident subject → inspect what they claim → compare individual expressions → accept aspiration as present state',philosophy:['Possession before aspiration','Confidence through composition','Individuality inside a shared frame','Restraint can signal status'],designSpace:{density:42,emotion:78,exploration:54,authority:32,interaction:22,order:88},idolLens:{intimacy:28,worldbuilding:46,assertiveness:88,collectiveCoding:66,participation:24,transformation:64}
  },
  {
    id:'perfume-technology-choreography-system',brand:'Perfume',family:'Artist / Performance System',collectionType:'idol-era',era:'PERFUME × TECHNOLOGY',name:'Perfume — Technology as Choreography',oneLiner:'テクノロジーを見せ物として足さず、人・身体・光・データを一つの振付システムにする。',
    description:'Perfume公式が長年のステージを支えるテクノロジーを紹介し、ReframeではライゾマティクスのインタラクションデザインとMIKIKOの演出・振付を明示している点から、Human + Technologyを別レイヤーではなく一つのPerformance Systemとして読む。Like What?では、センサー・映像・照明・身体動作が同じタイムラインで同期するOrchestrated Interfaceへ抽象化する。',
    tags:['Technology as Choreography','Synchronization','Performance System','Human + Machine','Reframe'],uiParts:['Performance','Timeline','System','Visualization'],visual:['人とテクノロジーを別々の装飾層に分けず同じリズムで同期させる','反復・位置・時間差を主要な構成要素にする','光やデータ表示を身体動作への応答として見せる','未来感をネオン色だけで作らない'],useCases:['ライブ演出','インタラクティブ展示','データ可視化','メディアアート','リアルタイムUI'],avoid:['静的な商品カタログ','低遅延同期が不要な単純フォーム'],prompt:'Perfume × Technology / Reframeのように、テクノロジーを背景エフェクトとして足さず、人の動き・タイミング・空間・データを一つの振付として設計してください。画面上の変化には身体や時間との因果を持たせ、未来感を単なる発光表現に頼らないでください。',sourceLabel:'Perfume Official — Reframe / Technology',sourceUrl:'https://www.perfume-web.jp/news/detail.php?id=822',mock:'idol-perfume-tech',domain:'Culture / Performance Technology',medium:'Stage + Interactive Media',archetype:'Synchronized Human-machine Performance',interactionModel:'Observe human motion → system responds → patterns synchronize → perceive one integrated performance',philosophy:['Technology should disappear into choreography','Synchronization creates meaning','Human motion remains the primary clock','System behavior can be expressive'],designSpace:{density:62,emotion:72,exploration:76,authority:34,interaction:88,order:98},idolLens:{intimacy:32,worldbuilding:72,assertiveness:62,collectiveCoding:94,participation:40,transformation:58}
  },
  {
    id:'babymonster-fan-service-identity-ecosystem',brand:'BABYMONSTER',family:'Idol / Fan Service System',collectionType:'idol-era',era:'MONSTIEZ',name:'BABYMONSTER — Shared Fan Identity Ecosystem',oneLiner:'ファンクラブ、ショップ、チケット、限定コンテンツを、一つのファンIDで横断させる。',
    description:'MONSTIEZ (JP) IDがオンラインショップ、年額・月額ファンクラブ、オンラインくじ、POP-UP STORE予約など複数サービスを一つのログイン情報でつなぐ設計を、Fan Identity Infrastructureとして読む。コンテンツの華やかさより、継続的な関係を壊さないAccount Continuityが主役。',
    tags:['Shared Identity','Fan Account','Service Ecosystem','Membership Layers','Continuity'],uiParts:['Account','Membership','Shop','Ticket','Content Hub'],visual:['サービスごとに入口は分けてもログイン状態と個人情報は共有する','年額・月額・W会員などMembership Layerを視覚的に整理する','限定コンテンツを権利状態と結びつける','推しメン仕様など個人化をアカウント層に持たせる'],useCases:['ファンクラブ','会員制EC','複数サービス統合','イベントチケット','ロイヤルティ'],avoid:['匿名利用が中心のニュースサイト','単発キャンペーン'],prompt:'BABYMONSTERのMONSTIEZ IDのように、ショップ、会員、チケット、限定コンテンツを別サービスの寄せ集めにせず、一つのIdentity Layerで連続させてください。会員種別や権利差を分かりやすくしつつ、ユーザーが毎回プロフィールやログインをやり直さない構造にしてください。',sourceLabel:'BABYMONSTER — MONSTIEZ (JP) ID',sourceUrl:'https://babymonster-official.jp/s/ygbm/page/id_intro',mock:'idol-babymonster-id',domain:'Culture / Fan Service',medium:'Web + Mobile + Commerce + Ticketing',archetype:'Fan Identity Ecosystem',interactionModel:'Create shared identity → join service layer → access content/commerce → carry identity across services',philosophy:['Identity should survive service boundaries','Membership is an entitlement system','Continuity increases belonging','Personalization belongs above individual products'],designSpace:{density:76,emotion:66,exploration:42,authority:62,interaction:86,order:94},idolLens:{intimacy:78,worldbuilding:38,assertiveness:72,collectiveCoding:80,participation:94,transformation:44}
  },
  {
    id:'cutie-street-kawaii-maker-becoming',brand:'CUTIE STREET',family:'Idol / Identity System',collectionType:'idol-era',era:'KAWAII MAKER',name:'CUTIE STREET — Kawaii as Becoming',oneLiner:'「かわいい」は属性ではなく、なりたい自分を作っていく動詞になる。',
    description:'CUTIE STREETの「どんな私にもなれる、どんなところへだって行ける」と“KAWAII MAKER”という公式コンセプトを、Identity as Becomingとして抽象化する。FRUITS ZIPPERの色によるCollective Codingよりも、ユーザーやメンバーが「自分のかわいいを作る」生成プロセスに重心を置く。',
    tags:['KAWAII MAKER','Becoming','Identity Creation','Member Color','Possibility'],uiParts:['Identity','Choice','Profile','Collection'],visual:['完成したタイプ分類より、複数のなりたい状態を並べる','色・衣装・言葉を選択可能な素材として見せる','「あなたはこれ」ではなく「こうもなれる」というコピーを使う','メンバー差をテンプレートではなく選択肢の幅として見せる'],useCases:['プロフィール作成','アバター','ファッション','自己表現サービス','オンボーディング'],avoid:['資格判定','選択肢を狭める必要がある安全UI'],prompt:'CUTIE STREETの“KAWAII MAKER”のように、Identityを固定ラベルとして診断するのではなく、ユーザーが素材を選びながら「なりたい自分」を作る体験にしてください。選択後も別の可能性を閉じず、「どんな私にもなれる」という余白を残してください。',sourceLabel:'CUTIE STREET — PROFILE',sourceUrl:'https://cutiestreet.asobisystem.com/news/2/',mock:'idol-cutie-maker',domain:'Culture / Idol',medium:'Editorial + Fan Content',archetype:'Identity Becoming System',interactionModel:'See possible identities → choose fragments → assemble current self → keep alternatives open',philosophy:['Identity can be made','Possibility before categorization','Choice itself can be expressive','Kawaii is a practice, not a fixed trait'],designSpace:{density:72,emotion:96,exploration:92,authority:6,interaction:72,order:56},idolLens:{intimacy:86,worldbuilding:54,assertiveness:58,collectiveCoding:76,participation:82,transformation:92}
  },
  {
    id:'kawaii-lab-differentiated-kawaii-platform',brand:'KAWAII LAB.',family:'Culture / Brand Architecture',name:'KAWAII LAB. — Platform for Differentiated Kawaii',oneLiner:'同じ「KAWAII」を量産せず、共通思想の下で違うグループを生み分ける。',
    description:'KAWAII LAB.は「原宿から世界へ」を掲げ、アイドルの発掘・育成・輩出を行うプロジェクト。FRUITS ZIPPER、CANDY TUNE、CUTIE STREETなどが同じ傘の下にありながら、それぞれ別のコンセプトを持つ点を、Endorsed Brand Architectureとして読む。Like What?では、親ブランドがビジュアルを統一するのではなく、価値観・育成基盤・流通を共有しながら子ブランドの差異を最大化する仕組みに抽象化する。',
    tags:['Brand Architecture','Endorsed Brands','Kawaii Platform','Portfolio','From Harajuku to the World'],uiParts:['Architecture','Portfolio','Navigation','Identity'],visual:['親ブランドは子ブランドの色やロゴを上書きしない','共通思想と各グループ固有コンセプトを階層で分ける','一覧では差異が一目で分かるカード構造にする','共通イベントや育成基盤だけを横断レイヤーとして見せる'],useCases:['マルチブランド企業','クリエイターレーベル','学校・育成組織','プロダクトポートフォリオ'],avoid:['単一ブランドの厳格なVisual Identity','全商品を同じテンプレートに揃えるEC'],prompt:'KAWAII LAB.のように、親ブランドの共通思想を保ちながら、子ブランドを同じ見た目へ均質化しないBrand Architectureを設計してください。親は価値観・育成・横断イベントを担当し、各子ブランドには独自の語彙・色・世界観・ターゲットを持たせてください。',sourceLabel:'ASOBISYSTEM — KAWAII LAB. project',sourceUrl:'https://asobisystem.com/news/25158/',mock:'idol-kawaii-lab',domain:'Culture / Brand Portfolio',medium:'Brand Architecture + Fan Platform',archetype:'Endorsed Culture Portfolio',interactionModel:'Enter umbrella idea → compare distinct groups → move into a child identity → return through shared ecosystem',philosophy:['Shared values do not require shared appearance','Portfolio value comes from difference','Parent brand can enable rather than dominate','Architecture should make lineage legible'],designSpace:{density:68,emotion:84,exploration:86,authority:32,interaction:52,order:88}
  }
);
