window.LIKEWHAT_PATTERNS.push(
  {
    id:'illit-super-real-me-dreamy-everyday',brand:'ILLIT',family:'Idol / Concept Era',collectionType:'idol-era',era:'SUPER REAL ME',name:'ILLIT — SUPER REAL ME / Dreamy Everyday Surrealism',oneLiner:'現実のすぐ隣に、少しだけ夢が混ざる。',
    description:'ILLITのデビュー期を、完成されすぎたファンタジーではなく「日常に小さな非現実が差し込む」設計として読む。SUPER ME / REAL MEという二重性、ステッカーや私物感のあるパッケージ要素、親密な少女像を、Soft SurrealismとDiary-like Editorialへ抽象化する。',
    tags:['Soft Surrealism','Diary-like Editorial','Imperfect Cute','Dream Logic','Everyday Fantasy'],uiParts:['Editorial','Identity','Collection','Detail'],visual:['現実的な写真や余白の中に一つだけ非現実な違和感を置く','ステッカー・メモ・小物のような私物的断片を散らす','パステルだけに頼らず素材感と不均一さで柔らかさを作る','整列しすぎないが情報階層は壊さない'],useCases:['若年層向けブランド','ライフスタイルEditorial','ファン向けコンテンツ','柔らかなキャンペーン'],avoid:['制度的業務UI','高密度な監視ダッシュボード'],prompt:'ILLIT「SUPER REAL ME」期のように、現実の写真・日常的な断片を基盤にしつつ、一部だけ夢のような違和感を差し込んでください。かわいさをパステル一色で処理せず、ステッカー、私物、メモ、少し不均一な配置で親密さを作り、完成されすぎない余白を残してください。',sourceLabel:'ILLIT — SUPER REAL ME',sourceUrl:'https://illit-official.jp/Discography/659c7b4d954a',mock:'idol-illit-super-real',domain:'Culture / Idol',medium:'Editorial + Music Packaging',archetype:'Dreamy Everyday Editorial',interactionModel:'Notice familiar world → discover small surreal detail → browse fragments → form emotional association',philosophy:['Everyday before fantasy','Intimacy through imperfection','Small surprise over spectacle','Identity can stay unfinished'],designSpace:{density:54,emotion:78,exploration:84,authority:8,interaction:30,order:48},idolLens:{intimacy:90,worldbuilding:42,assertiveness:22,collectiveCoding:48,participation:44,transformation:88}
  },
  {
    id:'illit-not-cute-anymore-identity-reversal',brand:'ILLIT',family:'Idol / Concept Era',collectionType:'idol-era',era:'NOT CUTE ANYMORE',name:'ILLIT — NOT CUTE ANYMORE / Cute Refusal',oneLiner:'既存の「かわいい」を否定することで、かわいさの輪郭を更新する。',
    description:'タイトルそのものが、それまで期待されてきた「cute」像との距離を作るEra。ブランドを全面刷新するのではなく、既知の親密さを残しながら言葉・コラージュ・少し強い自己主張を足し、Identity Reversalとして差分を作る。',
    tags:['Identity Reversal','Cute Refusal','Collage','Self-definition','Controlled Friction'],uiParts:['Editorial','Identity','Collection','Statement'],visual:['従来の柔らかな要素の一部を意図的に残して対比を作る','短い否定文や宣言文を大きく扱う','コラージュや切り貼りで自己定義の揺れを見せる','黒や強い輪郭を差し込み、かわいさとの摩擦を作る'],useCases:['ブランド刷新','若年層キャンペーン','既存イメージからの転換','自己定義を扱うEditorial'],avoid:['全面リブランディングが必要な制度サービス','一貫性だけが重要な業務UI'],prompt:'ILLIT「NOT CUTE ANYMORE」のように、既存ブランドの記号を全て捨てず、その一部を残したまま否定・反転・コラージュを加えてください。「前と違う」を新しい色だけで表現せず、以前の期待との摩擦自体をデザイン要素にしてください。',sourceLabel:'ILLIT — NOT CUTE ANYMORE',sourceUrl:'https://illit-official.jp/Discography/28b57e53e0ed',mock:'idol-illit-not-cute',domain:'Culture / Idol',medium:'Editorial + Music Packaging',archetype:'Identity Reversal Editorial',interactionModel:'Recognize old identity → meet contradiction → compare signals → reinterpret brand',philosophy:['Identity evolves through contradiction','Refusal can be a design primitive','Continuity makes reversal legible','Cute is not a fixed visual style'],designSpace:{density:68,emotion:86,exploration:74,authority:14,interaction:34,order:38},idolLens:{intimacy:72,worldbuilding:48,assertiveness:68,collectiveCoding:50,participation:38,transformation:96}
  },
  {
    id:'illit-mamihlapinatapai-self-styling',brand:'ILLIT',family:'Idol / Concept Era',collectionType:'idol-era',era:'MAMIHLAPINATAPAI',name:'ILLIT — MAMIHLAPINATAPAI / Self-styling in Motion',oneLiner:'「私は何者？」を固定せず、支度・選択・揺れそのものをIdentityにする。',
    description:'2026年の4th Mini Album。GRWM / IT’S ME / FREE RIDERという形態名や、GRWM、It’s Meなどの収録曲を手がかりに、Identityを完成形ではなく「自分を作っている途中」として読む。Like What?では、選択肢や準備の断片が同時に見えるSelf-styling Editorialへ抽象化する。',
    tags:['Self-styling','Identity in Motion','GRWM','Layered Choice','Personal Editorial'],uiParts:['Editorial','Identity','Choice','Collection'],visual:['鏡・支度・選択肢を想起させる断片をレイヤー化する','一つの完成ビジュアルより複数の候補状態を同時に残す','服・アクセサリー・文字片のようなChoice Fragmentを使う','「選んだ結果」より「選んでいる途中」を画面に残す'],useCases:['ファッション','パーソナライズ','プロフィール編集','自己表現型サービス'],avoid:['単一正解へ最短で誘導するトランザクション','安全上選択肢を減らすべき操作'],prompt:'ILLIT「MAMIHLAPINATAPAI」のGRWM / IT’S ME / FREE RIDERという構造から、Identityを固定プロフィールではなく「選びながら作るもの」として設計してください。完成状態だけでなく候補・準備・試行の断片を残し、ユーザーが自分を編集している感覚を作ってください。',sourceLabel:'ILLIT — MAMIHLAPINATAPAI',sourceUrl:'https://illit-official.jp/Discography/e096cae3e959',mock:'idol-illit-mami',domain:'Culture / Idol',medium:'Editorial + Music Packaging',archetype:'Self-styling Identity Editorial',interactionModel:'See possible selves → combine fragments → try a stance → keep identity open',philosophy:['Identity is a process','Choice can stay visible','Preparation is part of expression','Multiplicity before finality'],designSpace:{density:72,emotion:80,exploration:90,authority:8,interaction:58,order:44},idolLens:{intimacy:84,worldbuilding:54,assertiveness:44,collectiveCoding:46,participation:54,transformation:94}
  },
  {
    id:'aespa-synthetic-myth-worldbuilding',brand:'aespa',family:'Idol / Worldbuilding',collectionType:'idol-era',era:'SYNK',name:'aespa — Synthetic Myth Worldbuilding',oneLiner:'UIが世界を説明するのではなく、UIそのものを世界設定の一部にする。',
    description:'aespa公式が掲げる「Avatar X Experience」とaspect、本人とae-aespaがSYNKする世界観を、Interface as Fictionとして抽象化する。情報表示、用語、状態、ナビゲーション自体がLoreを持ち、利用者はサイトを読むのではなく世界へ接続する。',
    tags:['Cyber Mythology','Avatar Identity','Interface as Fiction','Lore-driven Navigation','Synthetic World'],uiParts:['Worldbuilding','Identity','Navigation','Lore'],visual:['固有語を単なる見出しではなく世界のルールとして反復する','実在人物とアバターの二重性をレイヤーで見せる','状態表示や接続表現を物語設定と一致させる','暗い基盤に発光・高コントラストの情報層を重ねる'],useCases:['ゲーム世界観','エンタメIP','SFブランド','没入型イベント'],avoid:['公共手続き','説明責任が最優先の制度UI'],prompt:'aespaのように、世界観を説明文の背景設定として置くのではなく、ナビゲーション、状態名、接続表現、プロフィール構造そのものへLoreを埋め込んでください。ユーザーが「サイトを見ている」より「世界へSYNKしている」と感じる構造にしてください。',sourceLabel:'aespa JAPAN OFFICIAL — PROFILE',sourceUrl:'https://aespa-official.jp/',mock:'idol-aespa-synk',domain:'Culture / Idol',medium:'Digital Worldbuilding + Editorial',archetype:'Synthetic Myth Interface',interactionModel:'Enter fictional system → learn its vocabulary → connect identities → explore lore',philosophy:['Interface belongs to the fiction','Identity can have an avatar layer','Vocabulary creates world boundaries','System state can tell story'],designSpace:{density:74,emotion:90,exploration:92,authority:26,interaction:72,order:64},idolLens:{intimacy:22,worldbuilding:100,assertiveness:86,collectiveCoding:78,participation:48,transformation:80}
  },
  {
    id:'xg-awe-alien-fashion-editorial',brand:'XG',family:'Idol / Concept Era',collectionType:'idol-era',era:'AWE',name:'XG — AWE / Alien Fashion Editorial',oneLiner:'親しませるより先に、未知との遭遇そのものを魅力にする。',
    description:'XG公式はAWEを、新しい存在に出会うときの恐れと好奇心が混ざる「畏敬」の心理過程として説明する。Like What?では、読みやすさを保ちながらも異形・余白・不自然なクロップ・強いEditorial Typographyで距離と好奇心を同時に作るAlien Fashion Editorialへ抽象化する。',
    tags:['Awe','Alien Editorial','Otherness','Fashion Shock','Boundary Breaking'],uiParts:['Editorial','Identity','Collection','Worldbuilding'],visual:['人物を中央に安全に置かずクロップや余白で緊張を作る','異質な形状やテクスチャを一箇所だけ強く使う','大きなタイポと小さな注釈を極端に対比する','すぐ理解できない要素を残し、好奇心のための摩擦を作る'],useCases:['ファッション','音楽Editorial','先鋭ブランド','コンセプトキャンペーン'],avoid:['高齢者向け手続き','緊急時UI','誤解コストが高い金融操作'],prompt:'XG「AWE」のように、未知の存在に対する恐れと好奇心を同時に作ってください。全要素を親しみやすくせず、異形・余白・極端なクロップ・大きなタイポを使って少し距離を置き、理解不能ではなく「もっと見たい」摩擦に調整してください。',sourceLabel:'XG — 2nd Mini Album AWE',sourceUrl:'https://xgalx.com/en/xg/discography/',mock:'idol-xg-awe',domain:'Culture / Idol',medium:'Fashion Editorial + Music',archetype:'Alien Fashion Editorial',interactionModel:'Encounter unfamiliar signal → feel tension/curiosity → inspect details → accept new identity',philosophy:['Otherness can attract','Distance can create desire','Novelty needs controlled friction','Identity can resist familiar categories'],designSpace:{density:58,emotion:98,exploration:96,authority:16,interaction:42,order:46},idolLens:{intimacy:12,worldbuilding:92,assertiveness:96,collectiveCoding:72,participation:28,transformation:94}
  },
  {
    id:'fruits-zipper-new-kawaii-identity-coding',brand:'FRUITS ZIPPER',family:'Idol / Identity System',collectionType:'idol-era',era:'NEW KAWAII',name:'FRUITS ZIPPER — NEW KAWAII / Hyper-Kawaii Identity Coding',oneLiner:'全員が違うことを、色と記号で「全員らしさ」に変える。',
    description:'公式コンセプト「原宿から世界へ」「NEW KAWAII」を、Collective Individualityとして読む。多色・多人数・高い感情強度をノイズにせず、メンバーごとの色やキャラクター性を情報属性として使うことで、統一感を「同じ見た目」から「違いを識別できる共通ルール」へ置き換える。',
    tags:['NEW KAWAII','Member Color','Collective Individuality','Color Coding','Harajuku'],uiParts:['Identity','Cards','Collection','Navigation'],visual:['色を装飾ではなく誰の情報かを示す識別コードとして使う','多色でも同じコンポーネント規則を共有する','個別キャラクターを小さなアイコンやモチーフへ変換する','余白を減らしてもグルーピングで迷わせない'],useCases:['複数メンバーIP','コミュニティ','イベントサイト','多カテゴリメディア'],avoid:['厳粛な制度サービス','色覚情報だけに依存できない重要操作'],prompt:'FRUITS ZIPPERのNEW KAWAIIのように、統一感を「全員同じ」にせず、各メンバー・カテゴリの色や記号を強く保ったまま、共通コンポーネントとレイアウト規則で一つの世界にしてください。色は飾りではなく識別情報として使ってください。',sourceLabel:'ASOBISYSTEM — FRUITS ZIPPER',sourceUrl:'https://asobisystem.com/en/talent/fruitszipper/',mock:'idol-fruits-new-kawaii',domain:'Culture / Idol',medium:'Pop Editorial + Fan Content',archetype:'Color-coded Collective Identity',interactionModel:'Recognize shared system → identify member by code → move across individual content → return to group',philosophy:['Unity does not require sameness','Color can carry identity','Abundance can stay legible','Individuality strengthens the collective'],designSpace:{density:86,emotion:100,exploration:82,authority:6,interaction:62,order:56},idolLens:{intimacy:78,worldbuilding:62,assertiveness:76,collectiveCoding:100,participation:82,transformation:64}
  },
  {
    id:'le-sserafim-fearless-performance-minimalism',brand:'LE SSERAFIM',family:'Idol / Identity System',collectionType:'idol-era',era:'IM FEARLESS',name:'LE SSERAFIM — Fearless Performance Minimalism',oneLiner:'強さを、装飾の多さではなく姿勢・余白・短い宣言で見せる。',
    description:'公式プロフィールで示されるIM FEARLESSの自己確信と強い意志を、Performance Minimalismへ抽象化する。大きな身体像、短く断定的なコピー、直線的Hierarchy、余白によって「自信は説明しすぎない」という表現を作る。',
    tags:['IM FEARLESS','Performance Minimalism','Confidence','Athletic Elegance','Statement'],uiParts:['Hero','Editorial','Identity','Statement'],visual:['人物や身体性を大きく一枚で置く','コピーは短く断言し説明文を二段目へ下げる','色数より余白と明暗差で強度を作る','直線的なグリッドと大胆なクロップを使う'],useCases:['スポーツブランド','ファッション','パフォーマンス','自信を訴求するキャンペーン'],avoid:['大量比較EC','やさしい相談体験','情報探索そのものが目的のWiki'],prompt:'LE SSERAFIMのIM FEARLESSが持つ自己確信のように、強さを装飾過多で表現せず、大きな身体像、短い宣言、余白、直線的なHierarchyで作ってください。ユーザーに「説明されて納得する」より「存在感を先に感じる」順序を設計してください。',sourceLabel:'LE SSERAFIM OFFICIAL — PROFILE',sourceUrl:'https://www.le-sserafim.jp/profile',mock:'idol-lesserafim-fearless',domain:'Culture / Idol',medium:'Performance Editorial',archetype:'Assertive Performance Minimalism',interactionModel:'Meet strong statement → read body/pose → absorb short proof → continue',philosophy:['Confidence does not need decoration','Body can be hierarchy','Restraint can amplify force','Statement before explanation'],designSpace:{density:32,emotion:78,exploration:42,authority:30,interaction:28,order:92},idolLens:{intimacy:28,worldbuilding:38,assertiveness:100,collectiveCoding:62,participation:24,transformation:56}
  },
  {
    id:'mei-continuous-fan-relationship',brand:'ME:I',family:'Idol / Fan Service',collectionType:'idol-era',era:'FAN RELATIONSHIP',name:'ME:I — Continuous Fan Relationship Interface',oneLiner:'「見るファン」を、日々接触し続ける関係へ変える。',
    description:'ME:Iは国民プロデューサーによって選ばれた成り立ちを持ち、公式サイト自体もBLOG、MOVIE、PHOTO、MESSAGE、WEB RADIO、Q&Aなど多層の継続コンテンツを持つ。Like What?では、デビュー時の参加から日常接触、限定コンテンツ、チケットまでを一つのRelationship Loopとして捉える。',
    tags:['Fan Relationship','Participation','Content Ecosystem','Member Intimacy','Continuity'],uiParts:['Feed','Community','Content Hub','Ticket'],visual:['ニュースだけでなくメンバー発の小さな更新を同じホームに混ぜる','BLOG・PHOTO・Q&Aなど接触様式を複数持たせる','メンバー単位とグループ単位を往復できるようにする','イベント時だけでなく平時にも戻る理由を作る'],useCases:['ファンクラブ','クリエイターコミュニティ','会員サービス','スポーツクラブ'],avoid:['一度きりのLP','完全匿名で関係蓄積をしないサービス'],prompt:'ME:I公式サイトのように、ニュース配信だけで終わらず、BLOG・MOVIE・PHOTO・Q&A・RADIO・チケットのような異なる接触を一つの関係性へ統合してください。大型イベントの時だけ訪れるサイトではなく、小さな更新で日常的に戻る理由を作ってください。',sourceLabel:'ME:I OFFICIAL SITE',sourceUrl:'https://me-i.jp/',mock:'idol-mei-relationship',domain:'Culture / Idol',medium:'Fan Platform + App',archetype:'Continuous Fan Relationship Platform',interactionModel:'Discover member update → react/consume → return regularly → participate in event/ticket',philosophy:['Relationship is built between releases','Many small contacts beat one giant page','Participation creates ownership','Member intimacy can be structured'],designSpace:{density:82,emotion:80,exploration:78,authority:14,interaction:76,order:70},idolLens:{intimacy:96,worldbuilding:34,assertiveness:48,collectiveCoding:76,participation:100,transformation:52}
  }
);
