(function(){
  if(!window.LikeWhatUI)return;
  const base=window.LikeWhatUI.render;
  const esc=window.LikeWhatUI.esc;
  const slug=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'-');

  if(!document.getElementById('lw-tv-preview-style')){
    const style=document.createElement('style');
    style.id='lw-tv-preview-style';
    style.textContent=`
      .tv-ui{--tv-ink:#171716;--tv-paper:#f5f1e7;--tv-hot:#ef5a3c;--tv-cool:#4b67d1;position:relative;overflow:hidden;background:var(--tv-paper);color:var(--tv-ink);font-family:ui-sans-serif,system-ui,sans-serif}
      .tv-ui *{box-sizing:border-box}.tv-ui header{display:flex;align-items:center;justify-content:space-between;min-height:34px;padding:7px 10px;border-bottom:1px solid rgb(23 23 22 / 16%);font-size:8px;letter-spacing:.08em}.tv-ui header b{font-size:10px;letter-spacing:-.02em}.tv-ui main{height:calc(100% - 34px);padding:9px}.tv-ui small{font-size:7px;font-weight:800;letter-spacing:.12em}.tv-ui strong{letter-spacing:-.045em}.tv-chiprow{display:flex;gap:4px;flex-wrap:wrap}.tv-chiprow i{padding:3px 5px;border:1px solid currentColor;border-radius:999px;font-size:6px;font-style:normal;font-weight:800}.tv-grid{display:grid;gap:5px}.tv-box{border:1px solid rgb(23 23 22 / 18%);background:rgb(255 255 255 / 46%)}.tv-ui .accent{background:var(--tv-ink);color:white}.tv-caption{position:absolute;right:8px;bottom:8px;left:8px;padding:5px 7px;background:var(--tv-ink);color:#fff;font-size:8px;font-weight:900;text-align:center}.tv-clock{font-size:22px;font-weight:900;letter-spacing:-.06em}.tv-score{display:flex;align-items:end;justify-content:space-between;font-variant-numeric:tabular-nums}.tv-score b{font-size:22px}.tv-progress{height:5px;border-radius:999px;background:rgb(23 23 22 / 12%);overflow:hidden}.tv-progress i{display:block;width:68%;height:100%;background:var(--tv-hot)}
      .tv-talk-arena main{display:grid;place-items:center}.tv-arena{position:relative;width:88%;height:74%;border:1px solid currentColor;border-radius:50%}.tv-arena i{position:absolute;width:15px;height:15px;border:2px solid var(--tv-paper);border-radius:50%;background:var(--tv-ink)}.tv-arena i:nth-child(1){top:-7px;left:45%}.tv-arena i:nth-child(2){top:14%;right:-5px}.tv-arena i:nth-child(3){right:4%;bottom:8%}.tv-arena i:nth-child(4){bottom:-6px;left:44%;background:var(--tv-hot)}.tv-arena i:nth-child(5){bottom:8%;left:4%}.tv-arena i:nth-child(6){top:14%;left:-5px}.tv-arena b{position:absolute;inset:35% 20%;display:grid;place-items:center;border-radius:999px;background:var(--tv-hot);color:#fff;font-size:9px}
      .tv-morning-rundown main,.tv-morning-grid main{display:grid;grid-template-columns:72px 1fr;gap:7px}.tv-rundown{display:grid;grid-template-columns:repeat(2,1fr);gap:4px}.tv-rundown span{display:grid;place-items:center;min-height:28px;padding:3px;background:#fff;border:1px solid rgb(23 23 22 / 12%);font-size:7px;font-weight:800}.tv-timecol{display:flex;flex-direction:column;justify-content:space-between}.tv-timecol p{margin:0;font-size:7px;line-height:1.4}
      .tv-prank-reveal main{display:grid;grid-template-columns:1fr 38px 1fr;align-items:center;gap:5px}.tv-prank-reveal .tv-before,.tv-prank-reveal .tv-after{height:75%;border:1px solid currentColor;display:grid;place-items:center;font-size:8px}.tv-prank-reveal .tv-after{background:var(--tv-hot);color:#fff}.tv-prank-reveal em{font-size:7px;font-style:normal;font-weight:900;text-align:center}
      .tv-quiz-tension{--tv-ink:#10192f;--tv-paper:#0d1631;--tv-hot:#f1b43b;color:#f8f1db}.tv-quiz-tension header{border-color:rgb(255 255 255 / 18%)}.tv-quiz-tension main{display:grid;grid-template-columns:55px 1fr;gap:7px}.tv-ladder{display:flex;flex-direction:column-reverse;gap:2px}.tv-ladder i{padding:2px 3px;border:1px solid rgb(255 255 255 / 18%);font-size:6px;font-style:normal}.tv-ladder i:nth-child(4){border-color:var(--tv-hot);color:var(--tv-hot)}.tv-options{display:grid;grid-template-columns:1fr 1fr;gap:4px;align-content:end}.tv-options b{padding:6px;border:1px solid #7182b8;border-radius:999px;font-size:7px}.tv-options strong{grid-column:1/-1;align-self:start;font-size:13px}
      .tv-adventure-caption main{position:relative}.tv-route{position:absolute;inset:10px 15px 28px;border:1px dashed currentColor;border-radius:45% 30% 50% 25%;transform:rotate(-7deg)}.tv-route i{position:absolute;width:9px;height:9px;border-radius:50%;background:var(--tv-hot)}.tv-route i:first-child{top:12%;left:10%}.tv-route i:nth-child(2){top:45%;left:48%}.tv-route i:last-child{right:4%;bottom:5%}.tv-route b{position:absolute;top:30%;left:26%;font-size:18px;transform:rotate(7deg)}
      .tv-quiz-stair main{display:flex;align-items:end;justify-content:center;gap:2px;padding-bottom:10px}.tv-step{display:flex;width:17%;align-items:center;justify-content:center;border:1px solid currentColor;border-bottom:4px solid var(--tv-ink);font-size:6px;font-weight:900}.tv-step:nth-child(1){height:26%}.tv-step:nth-child(2){height:39%}.tv-step:nth-child(3){height:52%;background:var(--tv-hot);color:#fff}.tv-step:nth-child(4){height:66%}.tv-step:nth-child(5){height:82%}
      .tv-hypothesis-lab main{display:grid;grid-template-rows:auto 1fr auto;gap:6px}.tv-thesis{padding:7px;border:2px solid var(--tv-ink);font-size:12px;font-weight:950;text-align:center}.tv-testflow{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;align-items:center;gap:3px;font-size:7px}.tv-testflow b{padding:7px 3px;border:1px solid currentColor;text-align:center}.tv-verdict{text-align:right;font-size:8px;font-weight:900;color:var(--tv-hot)}
      .tv-topic-panel main{display:grid;grid-template-rows:auto 1fr;gap:7px}.tv-theme{font-size:15px;font-weight:950}.tv-people{display:flex;align-items:center;justify-content:space-around}.tv-people i{display:grid;width:24px;height:24px;place-items:center;border-radius:50%;background:var(--tv-ink);color:#fff;font-size:6px;font-style:normal}.tv-people i:nth-child(3){background:var(--tv-hot)}
      .tv-street-observation main{position:relative}.tv-mapline{position:absolute;inset:16px 12px 30px;border-top:1px solid currentColor;border-bottom:1px solid currentColor;transform:skewY(-8deg)}.tv-pin{position:absolute;top:30%;left:48%;font-size:22px}.tv-street-observation .tv-caption{background:#f3df42;color:#171716}
      .tv-long-project main{display:grid;grid-template-columns:44px 1fr;gap:8px}.tv-years{display:flex;flex-direction:column;justify-content:space-between;font-size:6px;font-weight:900}.tv-project{display:grid;gap:5px}.tv-project b{font-size:14px}.tv-milestones{display:grid;grid-template-columns:repeat(3,1fr);gap:3px}.tv-milestones i{height:30px;border:1px solid currentColor;background:linear-gradient(135deg,transparent 48%,currentColor 49% 51%,transparent 52%);opacity:.65}
      .tv-expert-presentation main{display:grid;grid-template-columns:1fr 58px;gap:6px}.tv-slide{padding:7px;border:1px solid currentColor}.tv-slide strong{display:block;margin:5px 0;font-size:13px}.tv-rating{display:flex;flex-direction:column;justify-content:center;gap:5px}.tv-rating b{padding:4px;border:1px solid currentColor;font-size:7px}.tv-rating b:last-child{background:var(--tv-hot);color:#fff}
      .tv-team-quiz main{display:grid;grid-template-rows:auto 1fr;gap:6px}.tv-teams{display:grid;grid-template-columns:1fr 1fr;gap:4px}.tv-teams b{padding:4px;text-align:center;border:1px solid currentColor;font-size:7px}.tv-answergrid{display:grid;grid-template-columns:repeat(5,1fr);gap:3px;align-items:center}.tv-answergrid i{display:grid;aspect-ratio:1;place-items:center;border:1px solid currentColor;font-size:7px;font-style:normal}.tv-answergrid i:nth-child(-n+3){background:var(--tv-hot);color:#fff}
      .tv-live-stage{--tv-paper:#171716;--tv-ink:#fff;--tv-hot:#ef4f67;color:#fff}.tv-live-stage header{border-color:#444}.tv-stage{height:58%;margin:3px 10%;background:radial-gradient(circle at 50% 10%,#fff 0 2%,transparent 3%),linear-gradient(110deg,#4e376c,#1c3156);clip-path:polygon(12% 0,88% 0,100% 100%,0 100%)}.tv-now{display:flex;justify-content:space-between;align-items:end;margin-top:5px}.tv-now strong{font-size:12px}.tv-now span{font-size:7px}
      .tv-news-depth main,.tv-news-authority main{display:grid;grid-template-columns:1fr 1fr;gap:5px}.tv-news-depth article,.tv-news-authority article{padding:6px;border:1px solid rgb(23 23 22 / 18%)}.tv-news-depth article:first-child,.tv-news-authority article:first-child{grid-column:1/-1}.tv-news-depth h3,.tv-news-authority h3{margin:4px 0;font-size:12px;line-height:1.1}.tv-news-depth p,.tv-news-authority p{margin:0;font-size:6px;line-height:1.4}.tv-news-authority{--tv-hot:#b92730}
      .tv-portrait-doc{--tv-paper:#181818;--tv-ink:#f5f1e7;color:#f5f1e7}.tv-portrait-doc header{border-color:#3d3d3d}.tv-portrait{height:65%;margin:4px 12%;background:linear-gradient(135deg,#595959,#1e1e1e);position:relative}.tv-portrait:after{position:absolute;right:14%;bottom:0;width:35%;height:75%;border-radius:45% 45% 0 0;background:#b9b3a8;content:''}.tv-portrait-doc main>strong{display:block;font-size:13px;margin:4px 0}
      .tv-sports-emotion main{display:grid;grid-template-rows:auto 1fr;gap:5px}.tv-game{display:flex;justify-content:space-between;padding:5px;border-bottom:2px solid var(--tv-ink)}.tv-game b{font-size:14px}.tv-playerstory{display:grid;grid-template-columns:44px 1fr;gap:6px}.tv-player{background:linear-gradient(160deg,#ccc,#555)}.tv-playerstory strong{font-size:10px}.tv-playerstory p{font-size:6px;line-height:1.5}
      .tv-business-news main{display:grid;grid-template-columns:1fr 1fr;gap:5px}.tv-market{grid-column:1/-1;display:flex;justify-content:space-between;padding-bottom:4px;border-bottom:1px solid currentColor;font-size:7px}.tv-chart{height:45px;border-left:1px solid currentColor;border-bottom:1px solid currentColor;position:relative}.tv-chart:after{position:absolute;inset:10px 4px;background:linear-gradient(165deg,transparent 0 30%,var(--tv-hot) 31% 34%,transparent 35% 50%,var(--tv-hot) 51% 54%,transparent 55%);content:''}.tv-business-news aside{font-size:7px;line-height:1.6}
      .tv-business-doc main{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;align-items:center}.tv-business-doc b{padding:8px 3px;border:1px solid currentColor;font-size:7px;text-align:center}.tv-business-doc b:nth-child(2){background:var(--tv-hot);color:#fff}.tv-business-doc span{text-align:center;font-size:6px}.tv-business-doc small{grid-column:1/-1;text-align:center}
      .tv-executive-interview main{display:grid;grid-template-columns:52px 1fr;gap:7px}.tv-guest{height:65px;background:linear-gradient(160deg,#ddd,#777);position:relative}.tv-guest:after{position:absolute;right:12px;bottom:0;width:25px;height:48px;border-radius:45% 45% 0 0;background:#444;content:''}.tv-q{font-size:11px;font-weight:900}.tv-evidence{display:grid;grid-template-columns:repeat(2,1fr);gap:3px;margin-top:6px}.tv-evidence b{padding:4px;border:1px solid currentColor;font-size:6px}
      .tv-live-variety main{display:grid;grid-template-columns:1fr 1fr;gap:4px}.tv-live-variety b{display:grid;place-items:center;border:1px solid currentColor;font-size:7px}.tv-live-variety b:first-child{grid-column:1/-1;font-size:13px;background:var(--tv-hot);color:#fff}.tv-live-variety b:last-child{grid-column:1/-1}
      .tv-sketch-chaos main{position:relative;background:repeating-linear-gradient(-12deg,transparent 0 13px,rgb(23 23 22 / 6%) 14px 15px)}.tv-chaoscard{position:absolute;padding:5px;border:2px solid currentColor;background:var(--tv-paper);font-size:7px;font-weight:900}.tv-chaoscard:nth-child(1){top:8px;left:8px;transform:rotate(-5deg)}.tv-chaoscard:nth-child(2){top:28px;right:8px;transform:rotate(7deg);background:var(--tv-hot);color:#fff}.tv-chaoscard:nth-child(3){bottom:9px;left:28px;transform:rotate(3deg)}.tv-chaoscard:nth-child(4){bottom:25px;right:36px;transform:rotate(-9deg)}
      .tv-timed-kitchen main{display:grid;grid-template-rows:auto 1fr auto;gap:4px}.tv-timer{text-align:center;font-size:20px;font-weight:950;font-variant-numeric:tabular-nums}.tv-kitchens{display:grid;grid-template-columns:1fr 1fr;gap:4px}.tv-kitchens div{padding:5px;border:1px solid currentColor}.tv-kitchens b{display:block;font-size:7px}.tv-kitchens i{display:block;height:20px;margin-top:5px;background:repeating-linear-gradient(90deg,currentColor 0 1px,transparent 1px 7px);opacity:.45}.tv-judge{text-align:center;font-size:7px;font-weight:900}
    `;
    document.head.appendChild(style);
  }

  const shell=(pattern,size,kind,inner)=>`<div class="mini-ui mini-ui--${size} tv-ui tv-${kind} theme-${slug(pattern.brand)}" data-brand="${esc(pattern.brand)}"><header><b>${esc(pattern.brand)}</b><span>TV / FORMAT</span></header><main>${inner}</main></div>`;
  const chips=items=>`<div class="tv-chiprow">${items.map(x=>`<i>${esc(x)}</i>`).join('')}</div>`;

  function tvRender(pattern,size){
    const kind=String(pattern.mock||'').replace(/^tv-/, '');
    if(!String(pattern.mock||'').startsWith('tv-'))return base(pattern,size);
    if(kind==='talk-arena')return shell(pattern,size,kind,`<div class="tv-arena">${'<i></i>'.repeat(6)}<b>GUEST</b></div>`);
    if(kind==='morning-rundown'||kind==='morning-grid')return shell(pattern,size,kind,`<div class="tv-timecol"><div class="tv-clock">7:24</div><p>NOW<br>LIVE / MORNING</p></div><div class="tv-rundown">${['NEWS','WEATHER','SPORT','LIFE','ENT','LOCAL'].map(x=>`<span>${x}</span>`).join('')}</div>`);
    if(kind==='prank-reveal')return shell(pattern,size,kind,`<div class="tv-before">NORMAL</div><em>WAIT<br>FOR IT<br>→</em><div class="tv-after">REVEAL!</div>`);
    if(kind==='quiz-tension')return shell(pattern,size,kind,`<div class="tv-ladder">${['¥100K','¥1M','¥5M','¥10M','¥20M'].map(x=>`<i>${x}</i>`).join('')}</div><div class="tv-options"><strong>FINAL ANSWER?</strong>${['A','B','C','D'].map(x=>`<b>${x} — OPTION</b>`).join('')}</div>`);
    if(kind==='adventure-caption')return shell(pattern,size,kind,`<div class="tv-route"><i></i><i></i><i></i><b>GO!</b></div><div class="tv-caption">MISSION → DETOUR → CHALLENGE</div>`);
    if(kind==='quiz-stair')return shell(pattern,size,kind,`${['05','04','03','02','01'].map(x=>`<div class="tv-step">${x}</div>`).join('')}`);
    if(kind==='hypothesis-lab')return shell(pattern,size,kind,`<div class="tv-thesis">「○○説」</div><div class="tv-testflow"><b>SETUP</b><span>→</span><b>TEST</b><span>→</span><b>RESULT</b></div><div class="tv-verdict">検証結果 →</div>`);
    if(kind==='topic-panel')return shell(pattern,size,kind,`<div class="tv-theme">今夜のテーマ。</div><div class="tv-people">${['A','B','C','D','E'].map(x=>`<i>${x}</i>`).join('')}</div>`);
    if(kind==='street-observation')return shell(pattern,size,kind,`<small>街で聞いた「○○の件」</small><div class="tv-mapline"></div><div class="tv-pin">●</div><div class="tv-caption">この人、ちょっと気になる。</div>`);
    if(kind==='long-project')return shell(pattern,size,kind,`<div class="tv-years"><b>2024</b><b>2025</b><b>2026</b></div><div class="tv-project"><small>PROJECT MEMORY</small><b>つくる。直す。続ける。</b><div class="tv-progress"><i></i></div><div class="tv-milestones"><i></i><i></i><i></i></div></div>`);
    if(kind==='expert-presentation')return shell(pattern,size,kind,`<div class="tv-slide"><small>MY WORLD</small><strong>知らない世界へ。</strong>${chips(['01','02','03'])}</div><div class="tv-rating"><b>定番</b><b>沼</b><b>推し</b></div>`);
    if(kind==='team-quiz')return shell(pattern,size,kind,`<div class="tv-teams"><b>TEAM A　120</b><b>TEAM B　100</b></div><div class="tv-answergrid">${['1','2','3','4','5','6','7','8','9','10'].map(x=>`<i>${x}</i>`).join('')}</div>`);
    if(kind==='live-stage')return shell(pattern,size,kind,`<div class="tv-stage"></div><div class="tv-now"><div><small>NOW PLAYING</small><strong>ARTIST / SONG</strong></div><span>LIVE ●</span></div>`);
    if(kind==='news-depth'||kind==='news-authority')return shell(pattern,size,kind,`<article><small>TOP STORY / LIVE</small><h3>いま起きていること。</h3><p>FACT → CONTEXT → WHAT NEXT</p></article><article><small>DATA</small><h3>42.8</h3><p>COMPARE / SOURCE</p></article><article><small>DEEP</small><h3>WHY?</h3><p>PEOPLE / PLACE / CAUSE</p></article>`);
    if(kind==='portrait-doc')return shell(pattern,size,kind,`<div class="tv-portrait"></div><small>PORTRAIT / ONE PERSON</small><strong>NAME — PROFESSION</strong>`);
    if(kind==='sports-emotion')return shell(pattern,size,kind,`<div class="tv-game"><b>3</b><span>FINAL</span><b>2</b></div><div class="tv-playerstory"><div class="tv-player"></div><div><small>PLAYER STORY</small><strong>この一球までの時間。</strong><p>RESULT → PLAY → PERSON → MEMORY</p></div></div>`);
    if(kind==='business-news')return shell(pattern,size,kind,`<div class="tv-market"><b>NIKKEI +1.2%</b><span>USD/JPY 148.2</span></div><div class="tv-chart"></div><aside><small>WHY IT MOVED</small><br>DATA<br>↓<br>COMPANY<br>↓<br>LIFE</aside>`);
    if(kind==='business-doc')return shell(pattern,size,kind,`<small>BUSINESS CHANGE</small><b>PROBLEM</b><span>→</span><b>PEOPLE</b><span>→</span><b>CHANGE</b>`);
    if(kind==='executive-interview')return shell(pattern,size,kind,`<div class="tv-guest"></div><div><small>LEADER / COMPANY</small><div class="tv-q">なぜ、その判断を？</div><div class="tv-evidence"><b>FIELD VTR</b><b>DATA</b><b>HISTORY</b><b>DECISION</b></div></div>`);
    if(kind==='live-variety')return shell(pattern,size,kind,`${['LIVE / OPEN','CORNER 01','CORNER 02','GUEST','TOMORROW'].map(x=>`<b>${x}</b>`).join('')}`);
    if(kind==='sketch-chaos')return shell(pattern,size,kind,`${['FORMAT','CHARACTER','PARODY','CALLBACK'].map(x=>`<div class="tv-chaoscard">${x}</div>`).join('')}`);
    if(kind==='timed-kitchen')return shell(pattern,size,kind,`<div class="tv-timer">42:18</div><div class="tv-kitchens"><div><b>IRON CHEF</b><i></i></div><div><b>CHALLENGER</b><i></i></div></div><div class="tv-judge">SECRET INGREDIENT → COOK → JUDGE</div>`);
    return base(pattern,size);
  }

  window.LikeWhatUI={...window.LikeWhatUI,render:(pattern,size='card')=>tvRender(pattern,size),esc};
})();
