(function(){
  if(!window.LikeWhatUI)return;
  const base=window.LikeWhatUI.render;
  const esc=window.LikeWhatUI.esc;
  const lines=(n=3)=>Array.from({length:n},(_,i)=>`<i class="w3-line" style="--w:${58+((i*17)%34)}%"></i>`).join('');
  const cells=(n=8,cls='')=>Array.from({length:n},(_,i)=>`<i class="${cls} c${i%6}"></i>`).join('');
  function render(pattern,size='card'){
    const cls=`mini-ui mini-ui--${size} wave3-ui theme-${String(pattern.brand).toLowerCase().replace(/[^a-z0-9]+/g,'-')}`;
    let inner='';
    switch(pattern.mock){
      case 'learning-path':inner=`<div class="w3-learning"><header><b>LEARN</b><span>🔥 27　◆ 540</span></header><main><aside><small>SECTION 4</small><strong>Everyday stories</strong><div class="path">${Array.from({length:5},(_,i)=>`<i class="node n${i}"><b>${i<3?'✓':'★'}</b></i>`).join('')}</div></aside><section><small>TODAY</small><b>Keep the streak alive</b><span>1 short lesson</span><em>START →</em></section></main></div>`;break;
      case 'personalized-media':inner=`<div class="w3-media"><header><b>HOME</b><span>⌕　＋</span></header><main><h3>Made for you</h3><div class="media-row">${cells(5,'album')}</div><h3>Jump back in</h3><div class="media-row small">${cells(5,'album')}</div></main><footer><i></i><span><b>Now playing</b><small>Personal mix</small></span><em>▶</em></footer></div>`;break;
      case 'template-editor':inner=`<div class="w3-canva"><header><b>Design</b><span>File　Resize　•••</span><em>Share</em></header><aside><strong>Templates</strong><div class="template-grid">${cells(6,'tpl')}</div></aside><main><div class="canvas"><b>YOUR<br>IDEA</b><span>MAKE IT VISIBLE</span></div></main><nav><i>T</i><i>□</i><i>◎</i><i>✦</i></nav></div>`;break;
      case '3d-workspace':inner=`<div class="w3-blender"><header><b>Layout</b><span>Modeling　Sculpting　UV Editing　Animation</span></header><main><section class="viewport"><div class="axis">X　Y　Z</div><div class="cube"><i></i><i></i><i></i></div><small>User Perspective</small></section><aside><b>Scene Collection</b>${Array.from({length:5},(_,i)=>`<span>▾ Object.${String(i+1).padStart(3,'0')}</span>`).join('')}</aside><div class="props"><b>Transform</b>${lines(4)}</div></main><footer>${Array.from({length:14},(_,i)=>`<i class="tick t${i%3}"></i>`).join('')}</footer></div>`;break;
      case 'session-grid':inner=`<div class="w3-ableton"><header><b>120.00</b><span>4/4　　▶　■　●</span><em>Session</em></header><main><aside>${Array.from({length:5},(_,i)=>`<b>${i+1}<small>${['DRUMS','BASS','SYNTH','VOCAL','FX'][i]}</small></b>`).join('')}</aside><section class="session-cells">${Array.from({length:25},(_,i)=>`<i class="clip ${[1,3,7,8,12,16,18,22].includes(i)?'on':''} ${i===12?'playing':''}"><span>${i===12?'▶':''}</span></i>`).join('')}</section></main><footer><span>Scene 03</span><b>● ● ● ●</b></footer></div>`;break;
      case 'vehicle-hmi':inner=`<div class="w3-tesla"><header><span>12:48</span><b>74 km/h</b><span>82%</span></header><main><section class="vehicle"><div class="car">▰</div><small>MODEL</small></section><section class="hmi-map"><i class="road r1"></i><i class="road r2"></i><i class="route"></i><b>↑</b><div class="turn">2.4 km<br><strong>Turn right</strong></div></section></main><footer><span>19°</span><i>♨</i><i>♫</i><i>▣</i><span>20°</span></footer></div>`;break;
      case 'transit-wayfinding':inner=`<div class="w3-tfl"><header><b>UNDERGROUND</b><span>Way out　→</span></header><main><div class="route-sign"><small>WESTBOUND</small><strong>Central line</strong><span>Oxford Circus　●──●　Bond Street</span></div><div class="direction"><b>←</b><section><small>Platforms 1–2</small><strong>Victoria line</strong><span>Southbound · Brixton</span></section></div><footer><i class="roundel"></i><span>Mind the gap between train and platform</span></footer></main></div>`;break;
      case 'finance-control':inner=`<div class="w3-monzo"><header><b>Good morning</b><span>•••</span></header><main><section class="balance"><small>CURRENT ACCOUNT</small><strong>£2,480.16</strong><span>£820 left for August</span></section><div class="money-actions"><i>↑<small>Pay</small></i><i>⇄<small>Move</small></i><i>◉<small>Card</small></i></div><section class="transactions"><b>Today</b>${Array.from({length:3},(_,i)=>`<div><i></i><span>${['Groceries','Transport','Transfer'][i]}</span><strong>-${[24.8,8.2,60][i]}</strong></div>`).join('')}</section></main></div>`;break;
      case 'enterprise-records':inner=`<div class="w3-salesforce"><header><b>CRM</b><span>⌕ Search records</span><em>＋</em></header><nav>Home　Accounts　Contacts　Opportunities</nav><main><section class="record-head"><small>ACCOUNT</small><h3>Acme Industries</h3><div><b>Owner</b><span>A. User</span><b>Status</b><span>Active</span></div></section><section class="record-body"><div class="tabs"><b>Related</b><span>Details</span><span>Activity</span></div><div class="record-grid">${Array.from({length:4},(_,i)=>`<article><small>${['CONTACTS','OPPORTUNITIES','CASES','NOTES'][i]}</small><b>${[8,4,2,13][i]}</b>${lines(2)}</article>`).join('')}</div></section></main></div>`;break;
      case 'community-channels':inner=`<div class="w3-discord"><aside class="servers">${Array.from({length:6},(_,i)=>`<i>${i+1}</i>`).join('')}</aside><aside class="channels"><b>CREATIVE CLUB</b><small>TEXT CHANNELS</small><span># general</span><span class="active"># critique</span><span># resources</span><small>VOICE CHANNELS</small><span>◉ Lounge</span><span>◉ Co-work</span></aside><main><header># critique <span>Design feedback</span></header><section>${Array.from({length:4},(_,i)=>`<div class="msg"><i></i><p><b>User ${i+1}</b>${lines(2)}</p></div>`).join('')}</section><footer>Message #critique　＋</footer></main></div>`;break;
      case 'activity-analysis':inner=`<div class="w3-strava"><header><b>Morning Run</b><span>•••</span></header><main><section class="activity-map"><i class="map-road a"></i><i class="map-road b"></i><i class="activity-route"></i><b>START</b></section><section class="activity-data"><div><b>10.42</b><small>km</small></div><div><b>47:18</b><small>time</small></div><div><b>4:32</b><small>/km</small></div></section><div class="activity-chart"><i></i></div><footer><b>3 achievements</b><span>Segments　Analysis　Splits</span></footer></main></div>`;break;
      case 'driver-dispatch':inner=`<div class="w3-uber"><div class="dispatch-map"><i class="street s1"></i><i class="street s2"></i><i class="dispatch-route"></i><b>↑</b><div class="traffic"></div></div><header><strong>Pickup in 4 min</strong><span>2.1 km</span></header><section class="job-card"><small>NEXT STOP</small><b>Shinjuku Station</b><span>South Gate · rider waiting</span><em>Navigate →</em></section><footer><i>☰</i><span>ONLINE · ¥8,420</span><i>◎</i></footer></div>`;break;
      case 'science-orbit':inner=`<div class="w3-nasa"><header><b>NASA EYES</b><span>MISSION · INSIGHT</span></header><main><section class="space"><i class="orbit o1"></i><i class="orbit o2"></i><b class="planet"></b><em class="probe">◆</em><span>drag to rotate</span></section><aside><small>SELECTED</small><h3>InSight</h3><p>Explore instruments and deployment.</p><div>${lines(3)}</div><b>EXPLORE →</b></aside></main></div>`;break;
      case 'voice-dialog':inner=`<div class="w3-alexa"><header><b>VOICE EXPERIENCE</b><span>● listening</span></header><main><div class="voice-turn user"><small>YOU</small><p>What’s on my calendar?</p></div><div class="waveform">${Array.from({length:22},(_,i)=>`<i style="--h:${10+((i*13)%36)}px"></i>`).join('')}</div><div class="voice-turn agent"><small>ASSISTANT</small><p>You have two events. The first starts at 10.</p><span>You can say “what’s next?”</span></div></main><footer>intent → response → next turn → recovery</footer></div>`;break;
      case 'readiness-dashboard':inner=`<div class="w3-oura"><header><b>TODAY</b><span>Aug 10</span></header><main><section class="readiness"><div class="score-ring"><b>84</b><small>READINESS</small></div><p><strong>Good</strong><span>Your balance is steady today.</span></p></section><section class="contributors"><b>Contributors</b>${[['HRV balance','Optimal'],['Sleep balance','Good'],['Recovery index','Fair']].map((x,i)=>`<div><span>${x[0]}</span><i><em style="width:${[88,72,58][i]}%"></em></i><small>${x[1]}</small></div>`).join('')}</section></main></div>`;break;
      default:return base(pattern,size);
    }
    return `<div class="${cls}" data-brand="${esc(pattern.brand)}">${inner}</div>`;
  }
  window.LikeWhatUI={...window.LikeWhatUI,render,esc};
})();
